// ゲーム開発者が akashic-pdi を意識しなくてよいようにするため、
// ゲーム開発者向け API で利用する型定義は akashic-engine 配下でエクスポートしなおす。
// 念のため akshic-pdi 全体はこれとは別に g.pdi でエクスポートすることに注意。
export {
	CommonOffset,
	CommonSize,
	CommonArea,
	CommonRect,
	ErrorLike,
	AssertionError,
	TypeMismatchError,
	AssetLoadError,
	Asset,
	AssetLoadHandler,
	AudioAsset,
	AudioAssetHint,
	AudioPlayer,
	AudioPlayerEvent,
	CompositeOperation,
	CompositeOperationString,
	FontFamily,
	FontWeight,
	FontWeightString,
	Glyph,
	GlyphArea,
	GlyphFactory,
	ImageAsset,
	ImageAssetHint,
	ImageData,
	Renderer,
	ResourceFactory,
	ScriptAsset,
	ShaderUniform,
	Surface,
	TextAsset,
	VideoAsset,
	VideoPlayer
} from "@akashic/akashic-pdi";
