name: Publish and Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 24

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish and Release
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Prepare
        run: |
          npm ci
          npm test
      - name: Publish and Release
        uses: akashic-games/action-release@73e73291f4895535d295782f10de1793e4f7828b # v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
